[[custom_groups]]
name = "🌠 节点选择"
type = "select"
rule = ["[]🗽 美国分流", "[]🎉 高速切换", "[]♾️ 无限流量", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "✈️ 手动切换"
type = "select"
rule = ["!!GROUPID=1!!(^(?!.*小兔).*$)", "!!GROUPID=0!!(.*)", "!!GROUPID=2!!(.*)"]

[[custom_groups]]
name = "🗨️ ChatGPT"
type = "select"
rule = [
    "[]🗽 美国分流",
    "GPT",
    "(^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|us|United States))(?!.*小兔).*)",
    "[]✈️ 手动切换",
    "[]🌠 节点选择",
]

[[custom_groups]]
name = "📺 哔哩哔哩"
type = "select"
rule = ["[]DIRECT", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📱 TikTok"
type = "fallback"
rule = ["[]🍙 日本高速", "[]🌠 节点选择", "[]✈️ 手动切换"]
url = "https://www.gstatic.com/generate_204"
interval = 660
lazy = true

[[custom_groups]]
name = "🍰 Dynamic"
type = "select"
rule = [
    "[]DIRECT",
    "[]🦄 随机路由",
    "[]♾️ 无限流量",
    "!!GROUPID=0!!(.*)",
    "!!GROUPID=2!!(.*)",
    "!!GROUPID=3!!(.*)",
    "!!GROUPID=1!!(^(?!.*小兔).*$)",
]

[[custom_groups]]
name = "💻 Google"
type = "select"
rule = ["[]🌠 节点选择", "[]🎉 高速切换", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "⛅ OneDrive"
type = "select"
rule = ["[]🎉 高速切换", "[]🌠 节点选择", "[]♾️ 无限流量", "[]DIRECT"]

[[custom_groups]]
name = "📽️ Netflix"
type = "select"
rule = [
    "[]🍙 日本高速",
    "[]🌈 香港高速",
    "!!GROUPID=1!!(^(?!.*小兔).*$)",
    "!!GROUPID=2!!(.*)",
    "!!GROUPID=0!!(.*)",
    "!!GROUPID=3!!(.*)",
]

[[custom_groups]]
name = "💾 Microsoft"
type = "select"
rule = ["[]DIRECT", "[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🌍 国外流媒体"
type = "select"
rule = ["[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🐳 漏网の鱼"
type = "select"
rule = ["[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]


[[custom_groups]]
name = "🎉 高速切换"
type = "url-test"
rule = ["[]🌈 香港高速", "[]🍙 日本高速", "[]🗽 美国分流"]
url = "https://www.gstatic.com/generate_204"
interval = 233
lazy = false
timeout = 5
tolerance = 157

[[custom_groups]]
name = "🌈 香港高速"
type = "load-balance"
rule = ["!!GROUPID=0!!(港|HK|hk|Hong Kong|HongKong|hongkong)"]
url = "https://www.gstatic.com/generate_204"
interval = 180
lazy = false
strategy = "consistent-hashing"

[[custom_groups]]
name = "🍙 日本高速"
type = "load-balance"
rule = ["!!GROUPID=0!!(日|东京|大阪|埼玉|JP|jp|Japan)"]
url = "https://www.gstatic.com/generate_204"
interval = 360
lazy = false
strategy = "consistent-hashing"

[[custom_groups]]
name = "🗽 美国分流"
type = "fallback"
rule = ["!!GROUPID=1!!(Reality)", "[]♾️ 无限流量"]
url = "https://www.gstatic.com/generate_204"
interval = 660
lazy = true

[[custom_groups]]
name = "♾️ 无限流量"
type = "load-balance"
rule = ["!!GROUPID=0!!(.*)"]
url = "https://www.gstatic.com/generate_204"
interval = 567
lazy = true
strategy = "consistent-hashing"

[[custom_groups]]
name = "🦄 随机路由"
type = "load-balance"
rule = [
    "(港|HK|hk|Hong Kong|HongKong|hongkong|日|东京|大阪|埼玉|JP|jp|Japan|台|新北|彰化|TW|tw|Taiwan|新加坡|新|坡|狮城|SG|sg|Singapore)",
]
url = "https://www.gstatic.com/generate_204"
interval = 233
lazy = true
strategy = "round-robin"
