[[custom_groups]]
name = "🌠 节点选择"
type = "select"
rule = ["[]🌈 香港高速", "[]🗽 美国分流", "[]🥓 纯净IP", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "✈️ 手动切换"
type = "select"
rule = ["!!GROUPID=0-1!!(^(?!.*小兔).*$)", "!!GROUPID=2!!(.*)"]

[[custom_groups]]
name = "🗨️ ChatGPT"
type = "select"
rule = ["[]🥓 纯净IP", "[]🗽 美国分流", "GPT", "[]🌠 节点选择"]

[[custom_groups]]
name = "📺 哔哩哔哩"
type = "select"
rule = ["[]DIRECT", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📱 TikTok"
type = "select"
rule = ["[]🍙 日本高速", "[]✈️ 手动切换", "[]🌠 节点选择", "[]🥓 纯净IP"]

[[custom_groups]]
name = "💻 Google"
type = "select"
rule = ["[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "💾 Microsoft"
type = "select"
rule = ["[]DIRECT", "[]🌠 节点选择", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🌍 国外流媒体"
type = "select"
rule = ["[]🗽 美国分流", "[]🥓 纯净IP", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🐳 漏网の鱼"
type = "select"
rule = ["[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]


[[custom_groups]]
name = "🌈 香港高速"
type = "load-balance"
rule = ["!!GROUPID=0!!(港|HK|hk|Hong Kong|HongKong|hongkong)"]
url = "https://www.gstatic.com/generate_204"
interval = 233
lazy = false
strategy = "consistent-hashing"

[[custom_groups]]
name = "🍙 日本高速"
type = "load-balance"
rule = ["!!GROUPID=0!!(日|东京|大阪|埼玉|JP|jp|Japan)"]
url = "https://www.gstatic.com/generate_204"
interval = 360
lazy = true
strategy = "consistent-hashing"

[[custom_groups]]
name = "🗽 美国分流"
type = "fallback"
rule = ["!!GROUPID=1!!(^(?=.*Reality)(?=.*洛杉矶).*)", "[]♾️ 无限流量"]
url = "https://www.gstatic.com/generate_204"
interval = 66
lazy = false

[[custom_groups]]
name = "🥓 纯净IP"
type = "load-balance"
rule = ["!!GROUPID=1!!(^(?!.*洛杉矶).*$)"]
url = "https://www.gstatic.com/generate_204"
interval = 12
lazy = false
strategy = "round-robin"

[[custom_groups]]
name = "♾️ 无限流量"
type = "load-balance"
rule = ["!!GROUPID=0-1!!(^(?!.*洛杉矶).*$)"]
url = "https://www.gstatic.com/generate_204"
interval = 567
lazy = true
strategy = "consistent-hashing"
