[[custom_groups]]
name = "🌠 节点选择"
type = "select"
rule = ["[]🛫 高速节点", "[]🗽 美国分流", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "✈️ 手动切换"
type = "select"
rule = ["[]🗽 美国分流", "!!GROUPID=1!!(.*)"]

[[custom_groups]]
name = "🗨️ ChatGPT"
type = "select"
rule = [
    "[]🗽 美国分流",
    "(GPT)",
    "[]🐸 台湾分流",
    "[]🍙 日本高速",
    "[]✈️ 手动切换",
    "[]🌠 节点选择"
]

[[custom_groups]]
name = "🍎 Apple"
type = "select"
rule = ["[]DIRECT", "[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📟 Xbox"
type = "select"
rule = ["[]DIRECT", "[]🌠 节点选择", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📺 哔哩哔哩"
type = "select"
rule = ["[]DIRECT", "[]🗽 美国分流", "[]🍙 日本高速", "[]🐸 台湾分流", "[]🌈 香港高速"]

[[custom_groups]]
name = "📱 抖音集团"
type = "select"
rule = ["[]DIRECT", "[]🗽 美国分流", "[]🍙 日本高速", "[]🌈 香港高速", "[]🐸 台湾分流", "[]🦁 新加坡分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📱 TikTok"
type = "select"
rule = ["[]🍙 日本高速", "[]🗽 美国分流", "[]🌠 节点选择", "[]🌈 香港高速", "[]🐸 台湾分流", "[]🦁 新加坡分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🛁 YouTube"
type = "select"
rule = ["[]🌠 节点选择", "[]🗽 美国分流", "[]🍙 日本高速", "[]🐸 台湾分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🕊️ X"
type = "select"
rule = ["[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "💻 Google"
type = "select"
rule = ["[]🌠 节点选择", "[]✈️ 手动切换", "[]🗽 美国分流"]

[[custom_groups]]
name = "Ⓜ️ Meta"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🎮 Steam"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "💾 Microsoft"
type = "select"
rule = ["[]📟 Xbox", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🍇 数据采集"
type = "select"
rule = ["[]DIRECT", "[]🍂 负载均衡", "!!GROUPID=0-1!!(^(?!.*(org|续费|备用|解锁|转用|更新|专用)).*)"]

[[custom_groups]]
name = "📽️ Netflix"
type = "select"
rule = [
    "[]🗽 美国分流",
    "!!GROUPID=1!!(港|HK|hk|Hong Kong|HongKong|hongkong|台|新北|彰化|TW|tw|Taiwan)", 
    "!!GROUPID=1!!(.*)"
]

[[custom_groups]]
name = "⛺ Adobe"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "💸 PayPal"
type = "select"
rule = ["[]🗽 美国分流", "[]DIRECT", "[]🌠 节点选择", "[]✈️ 手动切换"]

[[custom_groups]]
name = "⛅ OneDrive"
type = "select"
rule = ["[]♾️ 无限流量", "[]✈️ 手动切换", "[]🌠 节点选择", "[]DIRECT"]

[[custom_groups]]
name = "☁️ 国际Cloud"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🌍 国外流媒体"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]🐸 台湾分流", "[]🍙 日本高速", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🐳 漏网の鱼"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]


[[custom_groups]]
name = "🛫 高速节点"
type = "url-test"
rule = ["[]🎉 高速切换", "[]🦚 私有固定IP"]
url = "https://www.gstatic.com/generate_204"
interval = 37
lazy = false
timeout = 5
tolerance = 80

[[custom_groups]]
name = "🎉 高速切换"
type = "select"
rule = ["[]🍙 日本高速", "[]🌈 香港高速", "[]🗽 美国分流", "[]🐸 台湾分流", "[]🦁 新加坡分流"]

[[custom_groups]]
name = "🐸 台湾分流"
type = "url-test"
rule = ["!!GROUPID=1!!(台|新北|彰化|TW|tw|Taiwan)"]
url = "https://www.gstatic.com/generate_204"
interval = 83
lazy = true
timeout = 5
tolerance = 349

[[custom_groups]]
name = "🦁 新加坡分流"
type = "url-test"
rule = ["!!GROUPID=1!!(新加坡|新|坡|狮城|SG|sg|Singapore)"]
url = "https://www.gstatic.com/generate_204"
interval = 300
lazy = true
timeout = 5
tolerance = 347

[[custom_groups]]
name = "🗽 美国分流"
type = "fallback"
rule = ["!!GROUPID=2!!(^(?=.*Reality)(?=.*洛杉矶).*)", 
        "!!GROUPID=1!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|us|United States)"]
url = "https://www.gstatic.com/generate_204"
interval = 300
lazy = false

[[custom_groups]]
name = "🦚 私有固定IP"
type = "select"
rule = ["!!GROUPID=2!!(^(?i)(?:(?!小兔|cf).)*$)"]

[[custom_groups]]
name = "♾️ 无限流量"
type = "fallback"
rule = ["!!GROUPID=1!!(^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong))(?!.*GRPC)(?!.*hy2).*[^1]$)", 
        "!!GROUPID=1!!(.*)", 
        "!!GROUPID=2!!(^(?i)(?:(?!小兔|cf).)*$)"]
url = "https://www.gstatic.com/generate_204"
interval = 567
lazy = false

[[custom_groups]]
name = "🌈 香港高速"
type = "fallback"
rule = ["!!GROUPID=1!!(^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong))(?!.*GRPC)(?!.*hy2).*[^1]$)", 
        "!!GROUPID=1!!(港|HK|hk|Hong Kong|HongKong|hongkong)"]
url = "https://www.gstatic.com/generate_204"
interval = 50
lazy = false

[[custom_groups]]
name = "🍙 日本高速"
type = "fallback"
rule = ["!!GROUPID=1!!(^(?=.*(日|东京|大阪|埼玉|JP|jp|Japan)).*[^1]$)", 
        "!!GROUPID=1!!(日|东京|大阪|埼玉|JP|jp|Japan)"]
url = "https://www.gstatic.com/generate_204"
interval = 57
lazy = false

[[custom_groups]]
name = "🍂 负载均衡"
type = "load-balance"
rule = ["!!GROUPID=0-1!!(^(?!.*(org|续费|备用|解锁|转用|更新|专用)).*)", 
        "!!GROUPID=2!!(^(?i)(?:(?!小兔|cf).)*$)",
        "[]DIRECT"]
url = "https://www.gstatic.com/generate_204"
interval = 66
lazy = true
strategy = "round-robin"


