[[custom_groups]]
name = "🌠 节点选择"
type = "select"
rule = ["[]🗽 美国分流", "[]🍙 日本高速", "[]♾️ 无限流量", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "✈️ 手动切换"
type = "select"
rule = ["!!GROUPID=1!!(^(?!.*小兔).*$)", "!!GROUPID=0!!(.*)", "!!GROUPID=2!!(.*)"]

[[custom_groups]]
name = "🗨️ ChatGPT"
type = "select"
rule = ["[]🗽 美国分流", "GPT", "[]✈️ 手动切换", "[]🌠 节点选择"]

[[custom_groups]]
name = "📺 哔哩哔哩"
type = "select"
rule = ["[]DIRECT", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📱 TikTok"
type = "select"
rule = ["[]🍙 日本高速", "[]✈️ 手动切换", "[]🌠 节点选择"]

[[custom_groups]]
name = "🍰 Dynamic"
type = "select"
rule = [
    "[]DIRECT",
    "[]🦄 随机路由",
    "[]♾️ 无限流量",
    "!!GROUPID=0!!(.*)",
    "!!GROUPID=2!!(.*)",
    "!!GROUPID=3!!(.*)",
    "!!GROUPID=1!!(^(?!.*小兔).*$)",
]

[[custom_groups]]
name = "💻 Google"
type = "select"
rule = ["[]🌠 节点选择", "[]🗽 美国分流", "[]✈️ 手动切换"]

[[custom_groups]]
name = "📽️ Netflix"
type = "select"
rule = [
    "[]🍙 日本高速",
    "!!GROUPID=1!!(^(?!.*小兔).*$)",
    "!!GROUPID=2!!(.*)",
    "!!GROUPID=0!!(.*)",
    "!!GROUPID=3!!(.*)",
]

[[custom_groups]]
name = "💾 Microsoft"
type = "select"
rule = ["[]DIRECT", "[]🌠 节点选择", "[]✈️ 手动切换"]

[[custom_groups]]
name = "🌍 国外流媒体"
type = "select"
rule = ["[]🗽 美国分流", "[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]

[[custom_groups]]
name = "🐳 漏网の鱼"
type = "select"
rule = ["[]🌠 节点选择", "[]✈️ 手动切换", "[]DIRECT"]


[[custom_groups]]
name = "🍙 日本高速"
type = "load-balance"
rule = ["!!GROUPID=0!!(日|东京|大阪|埼玉|JP|jp|Japan)"]
url = "https://www.gstatic.com/generate_204"
interval = 360
lazy = true
strategy = "consistent-hashing"

[[custom_groups]]
name = "🗽 美国分流"
type = "fallback"
rule = ["!!GROUPID=1!!(^(?=.*Reality)(?=.*洛杉矶).*)", "[]♾️ 无限流量"]
url = "https://www.gstatic.com/generate_204"
interval = 660
lazy = true

[[custom_groups]]
name = "♾️ 无限流量"
type = "load-balance"
rule = ["!!GROUPID=0!!(.*)"]
url = "https://www.gstatic.com/generate_204"
interval = 567
lazy = true
strategy = "consistent-hashing"

[[custom_groups]]
name = "🦄 随机路由"
type = "load-balance"
rule = [
    "(港|HK|hk|Hong Kong|HongKong|hongkong|日|东京|大阪|埼玉|JP|jp|Japan|台|新北|彰化|TW|tw|Taiwan|新加坡|新|坡|狮城|SG|sg|Singapore)",
]
url = "https://www.gstatic.com/generate_204"
interval = 233
lazy = true
strategy = "round-robin"
