name: Update Module File

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 16 * * *' # 每天北京时间00:00运行（UTC时间16:00）

permissions:
  contents: write

jobs:
  update_module:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: |
        python script/generate_module.py
        cp module/beii.module /tmp/beii.module
        rm module/beii.module

    - name: Checkout release branch
      run: |
        git fetch origin
        git checkout release

    - name: Restore generated file
      run: |
        cp /tmp/beii.module beii.module

    - name: Ensure changes are detected
      run: |
        git add beii.module

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m 'Update beii.module' || echo "No changes to commit"
        git push --force https://x-access-token:${{ secrets.FULL_ACCESS_TOKEN }}@github.com/angwz/DomainRouter.git release
