name: Update Shadowrocket Conf File

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 17 * * *' # 每天北京时间01:00运行（UTC时间17:00）

permissions:
  contents: write

jobs:
  update_shadowrocket_conf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: |
        python script/generate_shadowrocket_conf.py
        cp conf/和好可以吗.conf /tmp/和好可以吗.conf
        rm conf/和好可以吗.conf

    - name: Checkout release branch
      run: |
        git fetch origin
        git checkout release

    - name: Restore generated file
      run: |
        cp /tmp/和好可以吗.conf 和好可以吗.conf

    - name: Ensure changes are detected
      run: |
        git add 和好可以吗.conf

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m 'Update 和好可以吗.conf' || echo "No changes to commit"
        git push --force https://x-access-token:${{ secrets.FULL_ACCESS_TOKEN }}@github.com/angwz/DomainRouter.git release
